[package]
name = "p009"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
partial-min-max = "0.4.0"
proconio = "0.4.3"
